### ISSUE TITLE
I want to use this software

### ISSUE THREAD

**Issue by unternet** [junhaideng/Golang-BBS#1]
I wish some of the documentation were in english, so I could read it.

**Comment by junhaideng** [comment]
> I wish some of the documentation were in english, so I could read it.

oh, yeah, configuration is simple, and in fact now some of the configuration listed in README.md is not widely used in the project, maybe you can try the Google translation now, and I believe that the Go code is easy to understand for you, if you have any question, just contact me ! (I create README_EN.md, hope to help you)
